//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.ComponentProduct = new HashSet<ComponentProduct>();
        }
    
        public string Id_Component { get; set; }
        public string Name_Component { get; set; }
        public Nullable<int> Id_SizeType { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Id_Provider { get; set; }
        public Nullable<int> Id_Image { get; set; }
        public Nullable<int> Id_ComponentType { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual ComponentType ComponentType { get; set; }
        public virtual ImageStockComponent ImageStockComponent { get; set; }
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentProduct> ComponentProduct { get; set; }
    }
}
