//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatingProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreatingProcess()
        {
            this.WorkerProcess = new HashSet<WorkerProcess>();
        }
    
        public int Number_Process { get; set; }
        public int Id_Product { get; set; }
        public string Process_Name { get; set; }
        public Nullable<int> Id_Workstation { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Workstation Workstation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerProcess> WorkerProcess { get; set; }
    }
}
