//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id_Document { get; set; }
        public string Type_Document { get; set; }
        public string Name_Document { get; set; }
        public int Id_Order { get; set; }
        public byte[] Doc_Source { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
