//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialProduct = new HashSet<MaterialProduct>();
        }
    
        public int Id_Material { get; set; }
        public string Name_Material { get; set; }
        public Nullable<int> Id_SizeType { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Id_Provider { get; set; }
        public Nullable<int> Id_Image { get; set; }
        public Nullable<int> Id_TypeMaterial { get; set; }
        public Nullable<decimal> Cost_Material { get; set; }
        public Nullable<int> Length_Material { get; set; }
        public string Description_Material { get; set; }
        public Nullable<int> Id_Standart { get; set; }
    
        public virtual ImageStockMaterial ImageStockMaterial { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual SizeType SizeType { get; set; }
        public virtual Standart Standart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProduct> MaterialProduct { get; set; }
    }
}
