//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int Id_OrderStatus { get; set; }
        public Nullable<int> Id_Status { get; set; }
        public Nullable<System.DateTime> Date_Change { get; set; }
        public Nullable<System.TimeSpan> Time_Change { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_OldStatus { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
