//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeObject
    {
        public int Id_SizeObject { get; set; }
        public string Name_SizeObject { get; set; }
        public Nullable<double> Value_SizeObject { get; set; }
        public Nullable<int> Id_SizeType { get; set; }
        public Nullable<int> Id_Product { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SizeType SizeType { get; set; }
    }
}
