//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporterCompany.MainDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransporterBaseEntities7 : DbContext
    {
        public TransporterBaseEntities7()
            : base("name=TransporterBaseEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveSession> ActiveSession { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Component> Component { get; set; }
        public virtual DbSet<ComponentProduct> ComponentProduct { get; set; }
        public virtual DbSet<ComponentType> ComponentType { get; set; }
        public virtual DbSet<CreatingProcess> CreatingProcess { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<ImageStockComponent> ImageStockComponent { get; set; }
        public virtual DbSet<ImageStockMaterial> ImageStockMaterial { get; set; }
        public virtual DbSet<ImageStockUser> ImageStockUser { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialProduct> MaterialProduct { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductPart> ProductPart { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SizeObject> SizeObject { get; set; }
        public virtual DbSet<SizeType> SizeType { get; set; }
        public virtual DbSet<Standart> Standart { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeWorkstation> TypeWorkstation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkerProcess> WorkerProcess { get; set; }
        public virtual DbSet<WorkshopIcons> WorkshopIcons { get; set; }
        public virtual DbSet<Workstation> Workstation { get; set; }
        public virtual DbSet<Icons> Icons { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
